import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header"; // Component names should start with uppercase
import Footer from "@/components/layout/footer"; // Component names should start with uppercase

import {
  ClerkProvider,
} from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <body>
          <Header /> {/* Use the actual component, not lowercase */}
          {children}
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
